INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M0001',N'ログオン画面を閉じてもよろしいですか？',N'終了確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M0002',N'ログアウトしてもよろしいですか？',N'終了確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M0003',N'販売管理システムを終了してよろしいですか？',N'終了確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M0004',N'顧客データを更新してよろしいですか？',N'更新確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M0005',N'ID又はパスワードが入力されていません。',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M0006',N'指定したID・PWは、一致しません。',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M0007',N'ログインIDは半角英数字入力です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M0008',N'ログインIDは６文字です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M0009',N'入力されたログインIDは既に存在しています',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M0010',N'ログインIDが入力されていません',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M0011',N'ログインPWは半角英数字入力です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M0012',N'ログインPWが入力されていません',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M0013',N'ログインID・ログインPWが一致しません',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M0014',N'新規ログインPWを入力してください',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M0015',N'ログインPWは８文字以上１０文字以下で入力してください',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M1001',N'顧客IDは半角数字入力です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M1002',N'顧客IDは６文字です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M1003',N'入力された顧客IDは既に存在しています',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M1004',N'顧客IDが入力されていません',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M1005',N'営業所IDは半角数字入力です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M1006',N'営業所IDは６文字です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M1007',N'入力された営業所IDは既に存在しています',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M1008',N'営業所IDが入力されていません',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M1009',N'顧客名は全角入力です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M1010',N'顧客名は50文字以下です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M1011',N'顧客名が入力されていません',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M1012',N'住所は50文字以下です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M1013',N'住所カナは半角カナ入力です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M1014',N'住所カナは100文字以下です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M1015',N'電話番号は半角数値入力です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M1016',N'電話番号は12文字以下です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M1017',N'郵便番号は半角数値入力です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M1018',N'郵便番号は7文字です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M1019',N'FAX番号は半角数値入力です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M1020',N'FAX番号は12文字以下です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M1021',N'顧客データを登録してよろしいですか？',N'追加確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M1022',N'顧客データを登録しました',N'追加確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M1023',N'顧客データ登録に失敗しました',N'追加確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M1024',N'入力された顧客IDは存在しません',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M1026',N'顧客データを更新しました',N'更新確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M1027',N'顧客データ更新に失敗しました',N'更新確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M1028',N'顧客データを削除してよろしいですか？',N'削除確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M1029',N'顧客データを削除しました',N'削除確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M1030',N'顧客データ削除に失敗しました',N'削除確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M2001',N'商品IDは半角英数字入力です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M2002',N'商品IDは6文字です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M2003',N'商品IDは既に存在しています',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M2004',N'商品IDが入力されていません',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M2005',N'メーカIDは半角英数字入力です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M2006',N'メーカIDは4文字です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M2007',N'メーカIDは既に存在しています',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M2008',N'メーカIDが入力されていません',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M2009',N'商品名は全角入力です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M2010',N'商品名は50文字以下です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M2011',N'商品名が入力されていません',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M2012',N'価格は半角数字入力です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M2013',N'価格が入力されていません',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M2014',N'価格は9文字以下です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M2015',N'安全在庫数が入力されていません',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M2016',N'安全在庫数は半角数字入力です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M2017',N'安全在庫数は4文字以下です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M2018',N'小分類IDが入力されていません',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M2019',N'小分類IDは2文字以下です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M2020',N'小分類IDは半角数字入力です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M2021',N'型番が入力されていません',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M2022',N'型番は20文字以下です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M2023',N'型番は半角英数で入力です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M2024',N'色は全角入力です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M2025',N'色は20文字以下です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M2026',N'色は入力されていません',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M2027',N'発売日が入力されていません',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M2028',N'発売日は半角数字入力です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M2029',N'商品データを登録してよろしいですか？',N'追加確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M2030',N'商品データを登録しました',N'追加確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M2031',N'商品データ登録に失敗しました',N'追加確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M2032',N'入力された商品CDは存在しません',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M2033',N'商品データを更新してよろしいですか？',N'更新確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M2034',N'商品データを更新しました',N'更新確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M2035',N'商品データ更新に失敗しました',N'更新確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M3001',N'在庫IDは半角英数字入力です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M3002',N'在庫IDを入力してください',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M3003',N'在庫IDは６文字以下です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M3004',N'安全在庫数が入力されていません',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M3005',N'安全在庫数は半角数字入力です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M3006',N'安全在庫数は4文字以下です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M4001',N'消費税率は半角数値入力です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M4002',N'消費税率が入力されていません',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M4003',N'改変日が設定されていません',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M4004',N'削除フラグが不確定の状態です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M4005',N'備考は80文字以下です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M4006',N'消費税データを登録してよろしいですか？',N'追加確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M4007',N'消費税データを登録しました',N'追加確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M4008',N'消費税データ登録に失敗しました',N'追加確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M4009',N'消費税IDは半角数値入力です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M4010',N'入力された消費税IDは存在しません',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M4011',N'消費税データを更新してよろしいですか？',N'更新確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M4012',N'消費税データを更新しました',N'更新確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M4013',N'消費税データ更新に失敗しました',N'更新確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M4014',N'入力された消費税IDは他で利用されているため削除できません',N'削除確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M4015',N'消費税データを削除してよろしいですか？',N'削除確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M4016',N'消費税データを削除しました',N'削除確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M4017',N'消費税データ削除に失敗しました',N'削除確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M4018',N'消費税データを削除してよろしいですか？',N'削除確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M4019',N'消費税データを削除しました',N'削除確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M4020',N'消費税データ削除に失敗しました',N'削除確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M4021',N'消費税IDが入力されていません',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M5001',N'店舗CDは半角英数字入力です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M5002',N'店舗CDは5文字です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M5003',N'入力された店舗CDは既に存在しています',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M5004',N'店舗CDが入力されていません',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M5005',N'店舗名は全角入力です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M5006',N'店舗名は25文字以下です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M5007',N'店舗名が入力されていません',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M5008',N'備考は80文字以下です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M5009',N'店舗名カナは半角カナ入力です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M5010',N'店舗名カナは50文字以下です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M5011',N'店舗名カナが入力されていません',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M5012',N'郵便番号は半角数値入力です ',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M5013',N'郵便番号は7文字です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M5014',N'住所は50文字以下です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M5015',N'住所カナは半角カナ入力です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M5016',N'住所カナは100文字以下です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M5017',N'電話番号は半角数値入力です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M5018',N'電話番号は12文字以下です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M5019',N'電話番号が入力されていません',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M5020',N'FAX番号は半角数値入力です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M5021',N'FAX番号は12文字以下です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M5022',N'メールアドレスの入力形式が不正です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M5023',N'メールアドレスは30文字以下です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M5024',N'店舗データを登録してよろしいですか？',N'追加確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M5025',N'店舗データを登録しました',N'追加確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M5026',N'店舗データ登録に失敗しました',N'追加確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M5027',N'入力された店舗CDは存在しません',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M5028',N'店舗データを更新してよろしいですか？',N'更新確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M5029',N'店舗データを更新しました',N'更新確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M5030',N'店舗データ更新に失敗しました',N'更新確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M5031',N'入力された店舗CDは他で利用されているため削除できません',N'削除確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M5032',N'店舗データを削除してよろしいですか？',N'削除確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M5033',N'店舗データを削除しました',N'削除確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M5034',N'店舗データ削除に失敗しました',N'削除確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M6001',N'社員IDは半角数字入力です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M6002',N'社員IDは６文字です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M6003',N'入力された社員IDは既に存在しています',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M6004',N'社員IDが入力されていません',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M6005',N'社員名は全角入力です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M6006',N'社員名は50文字以下です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M6007',N'社員名が入力されていません',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M6008',N'社員名カナは半角カナ入力です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M6009',N'社員名カナは50文字以下です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M6010',N'社員名カナが入力されていません',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M6011',N'社員データを登録してよろしいですか？',N'追加確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M6012',N'社員データを登録しました',N'追加確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M6013',N'社員データ登録に失敗しました',N'追加確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M6014',N'社員データを更新してよろしいですか？',N'更新確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M6015',N'社員データを更新しました',N'更新確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M6016',N'社員データ更新に失敗しました',N'更新確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M6017',N'社員データを削除してよろしいですか？',N'削除確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M6018',N'社員データを削除しました',N'削除確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M6019',N'社員データの削除に失敗しました',N'削除確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M6020',N'入力された社員IDは他で利用されているため削除できません',N'削除確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M7001',N'日付は半角英数字です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M7002',N'日付が入力されていません',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M7003',N'入力可能な日付を入力してください',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M8001',N'入出荷IDが入力されていません',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M8002',N'入出荷IDは半角数字入力です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M8003',N'入出荷IDは6文字です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M8004',N'入荷状態を更新しますか',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M8005',N'入荷状態を更新しますか',N'更新確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M8006',N'出荷状態を更新しますか',N'更新確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M8007',N'出荷状態を更新しました',N'更新確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M9001',N'入出庫IDが入力されていません',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M9002',N'入出庫IDは半角数字入力です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M9003',N'入出庫IDは6文字です',N'入力確認確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M9004',N'入庫状態を更新しますか',N'更新確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M9005',N'入庫状態を更新しました',N'更新確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M9006',N'出庫状態を更新しますか',N'更新確認',1)
INSERT INTO M_Message(MsgCD,MsgComments,MsgTitle,MsgButton,MsgICon)
VALUES (N'M9007',N'出庫状態を更新しました',N'更新確認',1)
